### ISSUE TITLE
What happens when the browser is in a mobile device?

### ISSUE THREAD

**Issue by skytreader** [alex/what-happens-when#10]
We have a nice paragraph on what happens to the Enter key but what if the Enter key concerned is on a touchscreen of a mobile device? I'm not a hardware guy but I'm sure a lot of the events described in current repo head will not apply.

(Nitpicking, sure, but interviewers aren't exactly known to be forgiving. Cheers.)

**Comment by phildini** [comment]
I think this is answered by #104. Feel free to reopen if I'm wrong.
