### ISSUE TITLE
Part 7: Entry in NSA database

### ISSUE THREAD

**Issue by nickdesaulniers** [alex/what-happens-when#15]
just trolling :P

**Comment by alex** [comment]
I'd love a PR that discusses the security implications of various things, and how an attacker on the wire can observe and mutate requests (and how TLS protects against that) -- but I'm going to close this ticket for now :-)

**Comment by nickdesaulniers** [comment]
heh, on a more serious note, maybe talk a little about ip routing and how packets find their way from localhost to the IP address provided by DNS lookup.  BGP tables, core routers.  Also for DNS, you might have round robin, or geolocation based results.  There's also the driver for the NIC, and some complex timing in the kernal for receiving.
