### ISSUE TITLE
Spanish translation request

### ISSUE THREAD

**Issue by JoseDeFreitas** [alex/what-happens-when#311]
Hello 👋.
I'm a native Spanish speaker who has previously contributed to the translation of other open-source projects and I would want to translate this one into Spanish too. I found it really great, it'd be a pleasure working on it. I can keep the translation updated.
I'm opening an issue first to know if you are interested in the translation, as well as to make sure there isn't a Spanish translation yet (I've done a little research and didn't find anything).
Let me know what you think ✌.

**Comment by Myhinditracks** [comment]
This is a nice blog i must say, usually i don????t post comments on others???? blogs but would like to say that this post really forced me to do so!
Download<a href="https://www.myhinditracks.com/2022/01/dil-pe-zakham.html"> Dil Pe Zakham Khate Hain Jubin Nautiyal Mp3 Song</a>Download<a href="https://www.myhinditracks.com/2022/01/das-ki-kariye.html"> Das Ki Kariye Chiraag Mp3 Song</a>

**Comment by Myhinditracks** [comment]
Download<a href="https://www.myhinditracks.com/2022/01/dil-pe-zakham.html"> Dil Pe Zakham Khate Hain Jubin Nautiyal Mp3 Song</a>

**Comment by JoseDeFreitas** [comment]
Hello. I'm no longer interested in translating the content of this repository into Spanish. If someone else wants to do it, go ahead!
