### ISSUE TITLE
Open Source World's "How it works" Documentaries  

### ISSUE THREAD

**Issue by orges** [alex/what-happens-when#49]
Hello Alex,

It's a brilliant idea!!!  So people can contribute to this topic according to their expertise.

But why did you dedicate this repository only to "What happens when you type google.com"?
Isn't it fascinating  to see people are collaboratively working on materials like: what-happens-when/you-type-google.com which has internal links to what-happens-when/you-display-a-html-page-with-js-css  what-happens-when/you-add-robots.txt-to-your-site what-happens-when/you-fork-a-repository-on-github what-happens-when/you-play-online-x-mmog etc... ?

**Comment by orges** [comment]
After watching this repo for 7 hours, now it sounds impossible to me to maintain such structure in a personal repo :D

**Comment by alex** [comment]
Yeah, I'm going to close this, if someone else wants to pursue this, that'd be cool, but it's beyond the scope of this project.
