### ISSUE TITLE
What's the purpose of .travis.yml ?

### ISSUE THREAD

**Issue by michalskuza** [alex/what-happens-when#79]
as in the title what's the purpose of .travis.yml ?

**Comment by aprescott** [comment]
To run Travis builds? https://travis-ci.org/alex/what-happens-when

**Comment by michalskuza** [comment]
thanks, I wasn't familiar with that tool.

**Comment by aprescott** [comment]
The `doc8` command in `.travis.yml` gets run by Travis, as a way of double-checking that the formatting is fine on every new commit, etc. :)
